apiVersion: apps/v1
kind: Deployment
metadata:
  name: shailendra-nagpapp-deployment
  namespace: kubernetes-cluster-shailendrasharma
  labels:
    app: nagpapp
spec:
  template:
    metadata:
      name: shailendra-nagpapp-pod-m
      namespace: kubernetes-cluster-shailendrasharma
      labels:
        app: nagpapp
    spec:
      containers:
      - name: shailendra-nagpapp-container-m
        image: shailu0287/jenkins:latest
        ports:
          - containerPort: 80
            protocol: TCP
  replicas: 4
  selector:
    matchLabels:
      app: nagpapp
---
apiVersion: v1
kind: Service
metadata:
  name: nagpapp-service
spec:  
  type: NodePort
  selector:
    app: nagpapp
  ports:
    - protocol: TCP
      port: 80
      targetPort:80
      nodePort: 30157